# MobileApps page-manipulation service

swagger: 2.0
paths:
  /mobile-sections/{title}:
    get:
      tags:
        - Mobile
      summary: Get mobile-optimized HTML sections for a title.
      description: |
        Retrieve the latest HTML for a page title optimised for viewing with
        native mobile applications. Note that the output is split by sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: JSON containing HTML sections and metadata for the given page title.
          schema:
            type: object
            # FIXME!
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - access_check:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
          from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/mobile-sections/{title}
              headers:
                cache-control: '{{cache-control}}'
            return: 
              status: '{{from_backend.status}}'
              headers: '{{ merge({"cache-control": "s-maxage: 3600, max-age: 3600"}, from_backend.headers) }}'
              body: '{{from_backend.body}}'
      x-monitor: true
      x-amples:
        - title: Get MobileApps Foobar page
          request:
            params:
              domain: en.wikipedia.org
              title: Foobar
          response:
            status: 200
            headers:
              content-type: /application\/json/
            body:
              lead: /.+/
              remaining: /.+/

  /mobile-sections-lead/{title}:
    get:
      tags:
        - Mobile
      summary: Get mobile-optimized HTML lead section and metadata for a title.
      description: |
        Retrieve the lead section of the latest HTML for a page title optimised
        for viewing with native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: The HTML for the given page title.
          schema:
            type: object
            # FIXME!
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - access_check:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
          from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/mobile-sections-lead/{title}
            return: 
              status: '{{from_backend.status}}'
              headers: '{{ merge({"cache-control": "s-maxage: 3600, max-age: 3600"}, from_backend.headers) }}'
              body: '{{from_backend.body}}'
      x-monitor: false

  /mobile-sections-remaining/{title}:
    get:
      tags:
        - Mobile
      summary: Get non-lead mobile-optimized HTML sections for a title.
      description: |
        Retrieve the remainder of the latest HTML (without the lead section) for
        a page title optimised for viewing with native mobile applications,
        provided as a JSON object containing the sections.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: JSON wrapping HTML sections for the given page title.
          schema:
            type: object
            # FIXME!
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"
        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - access_check:
            request:
              method: get
              uri: /{domain}/sys/page_revisions/page/{title}
          from_backend:
            request:
              method: get
              uri: /{domain}/sys/mobileapps/mobile-sections-remaining/{title}
            return: 
              status: '{{from_backend.status}}'
              headers: '{{ merge({"cache-control": "s-maxage: 3600, max-age: 3600"}, from_backend.headers) }}'
              body: '{{from_backend.body}}'
      x-monitor: false

  /mobile-text/{title}:
    get:
      tags:
        - Mobile
      summary: Get mobile-optimized text and metadata for a title.
      description: |
        Retrieve the *lite* (text-only) version of the latest HTML for a page
        title optimised for viewing with native mobile applications.

        Stability: [experimental](https://www.mediawiki.org/wiki/API_versioning#Experimental). Don't rely on this.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: true
      responses:
        '200':
          description: >
            JSON comprising the HTML and various page attributes for the given page title.
          schema:
            type: object
          headers:
            ETag:
              description: >
                Syntax: "{revision}/{tid}".
                Example: "701384379/154d7bca-c264-11e5-8c2f-1b51b33b59fc"

        '404':
          description: Unknown page title
          schema:
            $ref: '#/definitions/problem'
        default:
          description: Error
          schema:
            $ref: '#/definitions/problem'
      x-request-handler:
        - from_backend:
            request:
              method: get
              uri: '{{options.host}}/{domain}/v1/page/mobile-text/{title}'
              headers:
                cache-control: '{{cache-control}}'
            return:
              status: '{{from_backend.status}}'
              headers: '{{ merge({"cache-control": "s-maxage: 3600, max-age: 3600"}, from_backend.headers) }}'
              body: '{{from_backend.body}}'
      x-monitor: false
