swagger: '2.0'
info:
  version: '1.0.0'
  title: RESTBase
  description: Distributed storage with REST API & dispatcher for backend service
  termsOfService: https://github.com/wikimedia/restbase#restbase
  contact:
    name: Services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/Services
  license:
    name: GNU Affero
    url: http://opensource.org/licenses/AGPL-3.0
host: localhost:7231
basePath: /v1
schemes:
  - http
paths:
  /{domain}/pages/{title}/html/:
    get:
      tags:
        - Page content
      description: Returns the list of revisions
      operationId: listRevisions
      produces:
        - application/json
      parameters:
        - name: domain
          in: path
          description: The domain under which the data resides
          type: string
          required: true
          default: en.wikipedia.org
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
      responses:
        '200':
          description: The list of revisions
          schema:
            type: array
            items:
              $ref: '#/definitions/revisions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-amples:
        - prerequisites:
            - method: put
              uri: /v1/en.wikipedia.test.local
              headers:
                content-type: application/json
              body: {}
            - method: put
              uri: /v1/en.wikipedia.test.local/page
              headers:
                content-type: 'application/json'
              body:
                type: 'pagecontent'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/76f22880-362c-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/9843f080-3443-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/b9f3f880-8153-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
          request:
            params:
                domain: en.wikipedia.test.local
                title: Foobar
          response:
            status: 200
            headers:
                content-type: application/json
                content-length: "128"
            body:
              items:
                - b9f3f880-8153-11e4-9234-0123456789ab
                - 76f22880-362c-11e4-9234-0123456789ab
                - 9843f080-3443-11e4-9234-0123456789ab
  /{domain}/pages/{title}/html:
    get:
      tags:
        - Page content
      description: Redirects to the latest html
      operationId: getLatestFormat
      parameters:
        - name: domain
          in: path
          description: The domain under which the data resides
          type: string
          required: true
          default: en.wikipedia.org
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
      responses:
        '302':
          description: Redirection to the latest html
        '404':
          description: Unknown table, bucket, or domain
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-amples:
        - prerequisites:
            - method: put
              uri: /v1/en.wikipedia.test.local
              headers:
                content-type: application/json
              body: {}
            - method: put
              uri: /v1/en.wikipedia.test.local/page
              headers:
                content-type: 'application/json'
              body:
                type: 'pagecontent'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/76f22880-362c-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/9843f080-3443-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
          request:
            params:
                domain: en.wikipedia.test.local
                title: Foobar
          response:
            status: 200
            headers:
                content-type: text/html; charset=UTF-8
  /{domain}/pages/{title}/data-parsoid/{revision}:
    get:
      tags:
        - Page content
      description: Returns the Parsoid data for the given revision
      operationId: getFormatRevision
      produces:
        - text/html
      parameters:
        - name: domain
          in: path
          description: The domain under which the data resides'
          type: string
          required: true
          default: en.wikipedia.org
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
        - name: revision
          in: path
          description: The revision
          type: string
          required: true
      responses:
        '200':
          description: The latest Parsoid data for the given page
        '400':
          description: Invalid revision
          schema:
            $ref: '#/definitions/invalidRevision'
        '404':
          description: Unknown table, bucket, page, or domain
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-amples:
        - prerequisites:
            - method: put
              uri: /v1/en.wikipedia.test.local
              headers:
                content-type: application/json
              body: {}
            - method: put
              uri: /v1/en.wikipedia.test.local/page
              headers:
                content-type: 'application/json'
              body:
                type: 'pagecontent'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/76f22880-362c-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
          request:
            params:
                domain: en.wikipedia.test.local
                title: Foobar
                revision: 76f22880-362c-11e4-9234-0123456789ab
          response:
            status: 200
            headers:
                etag: 76f22880-362c-11e4-9234-0123456789ab
                content-type: application/json; profile=mediawiki.org/specs/data-parsoid/1.0
                content-length: "25604"
        - request:
            params:
                domain: en.wikipedia.test.local
                title: Foobar
                revision: 624484477
          response:
            status: 200
            headers:
                etag: 76f22880-362c-11e4-9234-0123456789ab
                content-type: application/json; profile=mediawiki.org/specs/data-parsoid/1.0
                content-length: "25604"
  /{domain}/pages/{title}/html/{revision}:
    get:
      tags:
        - Page content
      description: Returns the html for the given revision
      operationId: getFormatRevision
      produces:
        - text/html
      parameters:
        - name: domain
          in: path
          description: The domain under which the data resides'
          type: string
          required: true
          default: en.wikipedia.org
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
        - name: revision
          in: path
          description: The revision
          type: string
          required: true
      responses:
        '200':
          description: The latest html for the given page
        '400':
          description: Invalid revision
          schema:
            $ref: '#/definitions/invalidRevision'
        '404':
          description: Unknown table, bucket, page, or domain
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-amples:
        - prerequisites:
            - method: put
              uri: /v1/en.wikipedia.test.local
              headers:
                content-type: application/json
              body: {}
            - method: put
              uri: /v1/en.wikipedia.test.local/page
              headers:
                content-type: 'application/json'
              body:
                type: 'pagecontent'
            - method: put
              uri: /v1/en.wikipedia.test.local/pages/Foobar/html/76f22880-362c-11e4-9234-0123456789ab
              headers:
                content-type: 'text/html; charset=UTF-8'
              body: 'Hello there'
          request:
            params:
                domain: en.wikipedia.test.local
                title: Foobar
                revision: 76f22880-362c-11e4-9234-0123456789ab
          response:
            status: 200
            headers:
                etag: 76f22880-362c-11e4-9234-0123456789ab
                content-type: text/html; charset=UTF-8
                content-length: "11"
            body: Hello there
definitions:
  defaultError:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  invalidRevision:
    required:
      - code
      - method
      - title
      - type
      - uri
    properties:
      code:
        type: integer
        format: int32
      method:
        type: string
      title:
        type: string
      type:
        type: string
      uri:
        type: string
  notFound:
    required:
      - code
      - method
      - title
      - type
      - uri
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      title:
        type: string
      description:
        type: string
      localURI:
        type: string
      table:
        type: string
      uri:
        type: string
      method:
        type: string
  revisions:
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string
