swagger: '2.0'
info:
  version: '1.0.0'
  title: MediaWiki Content API
  description: basic mediawiki content api.
  termsofservice: https://github.com/wikimedia/restbase#restbase
  contact:
    name: services
    email: services@lists.wikimedia.org
    url: https://www.mediawiki.org/wiki/services
  license:
    name: apache licence, v2
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:

  /{module:page}/:
    get:
      tags:
        - Page content
      description: List page properties / page content sub-apis
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'

  /{module:page}/title/:
    get:
      tags:
        - Page content
      description: List all known pages
      produces:
        - application/json
      responses:
        '200':
          description: The queriable list of page titles
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain or no pages to list
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        uri: /{domain}/sys/page_revisions/page/


  /{module:page}/title/{title}/:
    get:
      tags:
        - Page content
      description: > 
        List revisions for a title. Currently this lists all
        revisions that ever used this title, but eventually it should probably
        return the linear history (across renames) of the page currently using
        this title. Stability: experimental.
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: the title of page content
          type: string
          required: true
      responses:
        '200':
          description: The queriable list of page revisions
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain or page title
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        uri: /{domain}/sys/page_revisions/page/{title}/

  /{module:page}/html/:
    get:
      tags:
        - Page content
      description: List titles for which the HTML property is available
      produces:
        - application/json
      responses:
        '200':
          description: The queriable list of page titles
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain or no pages to list
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        uri: /{domain}/sys/page_revisions/page/

  /{module:page}/html/{title}:
    get:
      tags:
        - Page content
      description: Retrieve the latest html
      parameters:
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: the page's latest HTML
          schema: 'text/html'
        '404':
          description: unknown domain or page title
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        # Directly return the latest HTML. Alternatively, we could also try
        # relative redirects. A relative location header of 'foo/bar' seems to
        # work in current Chrome and Firefox.
        # See also http://tools.ietf.org/html/rfc7231#section-7.1.2
        uri: /{domain}/sys/parsoid/html/{title}

  /{module:page}/html/{title}/:
    get:
      tags:
        - Page content
      description: List all HTML revisions for a page
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
      responses:
        '200':
          description: The list of revisions
          schema:
            $ref: '#/definitions/revisions'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/html/{title}/


  /{module:page}/html/{title}/{revision}{/tid}:
    get:
      tags:
        - Page content
      description: Retrieve the html for a given revision (and optional timeuuid)
      operationId: getFormatRevision
      produces:
        - text/html
        - application/json
      parameters:
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
        - name: revision
          in: path
          description: The revision
          type: string
          required: true
        - name: tid
          in: path
          description: The revision's time ID
          type: string
          required: false
      responses:
        '200':
          description: The html for the given page, revision and tid
          schema: 'text/html'
        '400':
          description: Invalid revision
          schema:
            $ref: '#/definitions/invalidRevision'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: unknown domain, page, revision or tid
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/html/{title}/{revision}{/tid}

  /{module:page}/data-parsoid/:
    get:
      tags:
        - Page content
      description: List titles for which the data-parsoid property is available
      produces:
        - application/json
      responses:
        '200':
          description: The queriable list of page titles
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain or no pages to list
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        # Fixme: only list pages that have at least one revision with content
        # model 'wikitext'
        uri: /{domain}/sys/page_revisions/page/

  /{module:page}/data-parsoid/{title}:
    get:
      tags:
        - Page content
      description: Retrieve the latest data-parsoid (private Parsoid metadata)
      parameters:
        - name: title
          in: path
          description: the title of page content
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: data-parsoid JSON blob
          schema:
            $ref: '#/definitions/data-parsoid'
        '404':
          description: unknown domain or page title
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        uri: /{domain}/sys/parsoid/data-parsoid/{title}

  /{module:page}/data-parsoid/{title}/:
    get:
      tags:
        - Page content
      description: List data-parsoid revisions for a page
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
      responses:
        '200':
          description: The list of revisions
          schema:
            $ref: '#/definitions/revisions'
        '404':
          description: unknown domain or page title
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/data-parsoid/{title}/

  /{module:page}/data-parsoid/{title}/{revision}{/tid}:
    get:
      tags:
        - Page content
      description: Retrieve data-parsoid (internal Parsoid metadata) for a given page & revision
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: The title of page content
          type: string
          required: true
        - name: revision
          in: path
          description: The revision
          type: string
          required: true
        - name: tid
          in: path
          description: The revision's time ID
          type: string
          required: false
      responses:
        '200':
          description: The latest Parsoid data for the given page
          schema:
            $ref: '#/definitions/data-parsoid'
        '400':
          description: Invalid revision
          schema:
            $ref: '#/definitions/invalidRevision'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: unknown domain, page, revision or tid
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/data-parsoid/{title}/{revision}{/tid}

  /{module:page}/revision/:
    get:
      tags:
        - Page content
      description: List available revisions
      produces:
        - application/json
      responses:
        '200':
          description: The queriable sub-items
          schema:
            $ref: '#/definitions/listing'
        '404':
          description: unknown domain or no revisions to list
          schema:
            $ref: '#/definitions/notfound'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/defaulterror'
      x-backend-request:
        uri: /{domain}/sys/page_revisions/rev/

  /{module:page}/revision/{revision}:
    get:
      tags:
        - Page content
      description: Get meta-data about a specific revision
      produces:
        - application/json
      parameters:
        - name: revision
          in: path
          description: The revision id
          type: string
          required: true
      responses:
        '200':
          description: The revision's properties
          schema:
            $ref: '#/definitions/rev-schema'
        '400':
          description: Invalid revision
          schema:
            $ref: '#/definitions/invalidRevision'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: Unknown revision id or domain
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/page_revisions/rev/{revision}

  /{module:transform}/html/to/wikitext{/title}{/revision}:
    post:
      tags:
        - Transforms
      description: Transform HTML to wikitext
      consumes:
        - multipart/form-data
      produces:
        - text/plain; profile=mediawiki.org/specs/wikitext/1.0.0
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: false
        - name: revision
          in: path
          description: The page revision
          type: integer
          required: false
        - name: html
          in: formData
          description: The HTML to transform
          type: string
          required: true
      responses:
        '200':
          schema: 'text/plain'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: unknown domain, page or revision
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/transform/html/to/wikitext{/title}{/revision}

  /{module:transform}/wikitext/to/html{/title}{/revision}:
    post:
      tags:
        - Transforms
      description: Transform wikitext to HTML
      consumes:
        - multipart/form-data
      produces:
        - text/html; profile=mediawiki.org/specs/html/1.0.0
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: false
        - name: revision
          in: path
          description: The page revision
          type: integer
          required: false
        - name: wikitext
          in: formData
          description: The Wikitext to transform to HTML
          type: string
          required: true
        - name: bodyOnly
          in: formData
          description: Return only `body.innerHTML`
          type: boolean
          required: false
      responses:
        '200':
          schema: 'text/html'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: unknown domain, page or revision
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/transform/wikitext/to/html{/title}{/revision}

  /{module:transform}/html/to/html{/title}{/revision}:
    post:
      tags:
        - Transforms
      description: Update / refresh / sanitize HTML
      consumes:
        - multipart/form-data
      produces:
        - text/html; profile=mediawiki.org/specs/html/1.0.0
      parameters:
        - name: title
          in: path
          description: The page title
          type: string
          required: false
        - name: revision
          in: path
          description: The page revision
          type: integer
          required: false
        - name: html
          in: formData
          description: The HTML to transform
          type: string
          required: true
        - name: bodyOnly
          in: formData
          description: Return only `body.innerHTML`
          type: boolean
          required: false
      responses:
        '200':
          schema: 'text/html'
        '403':
          description: access to the specific revision is restricted
          schema:
            $ref: '#/definitions/httpError'
        '404':
          description: unknown domain, page or revision
          schema:
            $ref: '#/definitions/notFound'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/defaultError'
      x-backend-request:
        uri: /{domain}/sys/parsoid/transform/html/to/html{/title}{/revision}

definitions:
  defaultError:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  invalidRevision:
    required:
      - code
      - method
      - title
      - type
      - uri
    properties:
      code:
        type: integer
        format: int32
      method:
        type: string
      title:
        type: string
      type:
        type: string
      uri:
        type: string
  httpError:
    required:
      - method
      - title
      - type
      - detail
    properties:
      method:
        type: string
      title:
        type: string
      type:
        type: string
      detail:
        type: string
  notFound:
    required:
      - code
      - method
      - title
      - type
      - uri
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      title:
        type: string
      description:
        type: string
      localURI:
        type: string
      table:
        type: string
      uri:
        type: string
      method:
        type: string
  revisions:
    description: The result format for revision listing
    required:
      - items
    properties:
      items:
        type: array
        properties:
          revision:
            type: integer
            format: int32
          tid:
            type: string
  listing:
    description: The result format for listings
    required:
      - items
    properties:
      items:
        type: array
        items:
          type: string
  data-parsoid:
    description: Result format for Parsoid data queries
    required:
      - counter
      - ids
    properties:
      counter:
        type: integer
        format: int32
      ids:
        type: object
  rev-schema:
    description: Result format for revision items
    required:
      - count
      - items
    properties:
      count:
        type: integer
        format: int32
      items:
        type: array
        items:
          title:
            type: string
          rev:
            type: integer
            format: int32
          tid:
            type: string
          latest_rev:
            type: integer
            format: int32
          latest_tid:
            type: string
          nextrev_tid:
            type: string
          comment:
            type: string
          renames:
            type: array
            items:
              type: string
          restrictions:
            type: array
            items:
              type: string
          tags:
            type: array
            items:
              type: string
          user_id:
            type: integer
            format: int32
          user_text:
            type: string

